eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8081
  error:
    include-message: always

spring:
  application:
    name: TEACHER-APP
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 21423sq!
    url: jdbc:mysql://localhost:3306/paynav
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: 127.0.0.1
    port: 6379
  cache:
    type: redis



resilience4j:
  circuitbreaker:
    instances:
      student-fetch:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      student-fetch:
        max-attempts: 3
        wait-duration: 5s

  ratelimiter:
    instances:
      RateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 2s

